package pojo;
// Generated 29/09/2021 4:04:37 PM by Hibernate Tools 4.3.1

import DAO.DAOLogin;
import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;




/**
 * TblAdmin generated by hbm2java
 */
@ManagedBean
public class TblAdmin  implements java.io.Serializable {


     private Integer idAdmin;
     private String nama;
     private String alamat;
     private int usia;
     private String gender;
     private String noTelp;
     private String email;
     private String username;
     private String password;
     private Boolean loginGagal;
     private String loginMsg;
     private Boolean regisGagal;
     private String regisMsg;

    public TblAdmin() {
    }

    public TblAdmin(String nama, String alamat, int usia, String gender, String noTelp, String email, String username, String password) {
       this.nama = nama;
       this.alamat = alamat;
       this.usia = usia;
       this.gender = gender;
       this.noTelp = noTelp;
       this.email = email;
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public int getUsia() {
        return this.usia;
    }
    
    public void setUsia(int usia) {
        this.usia = usia;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getLoginGagal() {
        return loginGagal;
    }

    public void setLoginGagal(Boolean loginGagal) {
        this.loginGagal = loginGagal;
    }

    public String getLoginMsg() {
        return loginMsg;
    }

    public void setLoginMsg(String loginMsg) {
        this.loginMsg = loginMsg;
    }

    public Boolean getRegisGagal() {
        return regisGagal;
    }

    public void setRegisGagal(Boolean regisGagal) {
        this.regisGagal = regisGagal;
    }

    public String getRegisMsg() {
        return regisMsg;
    }

    public void setRegisMsg(String regisMsg) {
        this.regisMsg = regisMsg;
    }
    
    

public String validasiLogin(){
    DAOLogin uDao = new DAOLogin();
    List<TblAdmin> us = uDao.getBy(username, password);
    System.out.println(us);
    if(us.size() == 1) {
        System.out.println("BERHASIL MASUK");
        nama = us.get(0).nama;
        alamat = us.get(0).alamat;
        usia = us.get(0).usia;
        gender = us.get(0).gender;
        noTelp = us.get(0).noTelp;
        email = us.get(0).email;
        username = us.get(0).username;
        password = us.get(0).password;
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        HttpSession session = request.getSession();
        session.setAttribute("nama", us.get(0).nama);
        session.setAttribute("alamat", us.get(0).alamat);
        return "view_pelanggan";
    } 
    loginGagal = true;
    loginMsg = "Username atau Password Salah!";
    System.out.println("GAGAL MASUK");
    
    return "login";
}

public String logout(){
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        HttpSession session=request.getSession();  
               
            session.removeAttribute("nama");
            session.removeAttribute("alamat");
            session.invalidate();  
        return "homepage";
}


}


