package pojo;
// Generated 29/09/2021 4:04:37 PM by Hibernate Tools 4.3.1

import DAO.DAOMobil;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblMobil generated by hbm2java
 */
@ManagedBean
public class TblMobil  implements java.io.Serializable {


     private String idMobil;
     private String merek;
     private String tipe;
     private String warna;
     private String gambar;
     private int biaya;
     private Boolean gagalError;
     private Boolean gagalMsg;
     private String msgError;
     private String message;

    public TblMobil() {
    }

    public TblMobil(String idMobil, String merek, String tipe, String warna, int biaya, String gambar) {
       this.idMobil = idMobil;
       this.merek = merek;
       this.tipe = tipe;
       this.warna = warna;
       this.biaya = biaya;
       this.gambar = gambar;
    }

    public String getGambar() {
        return gambar;
    }

    public void setGambar(String gambar) {
        this.gambar = gambar;
    }
   
    public String getIdMobil() {
        return this.idMobil;
    }
    
    public void setIdMobil(String idMobil) {
        this.idMobil = idMobil;
    }
    public String getMerek() {
        return this.merek;
    }
    
    public void setMerek(String merek) {
        this.merek = merek;
    }
    public String getTipe() {
        return this.tipe;
    }
    
    public void setTipe(String tipe) {
        this.tipe = tipe;
    }
    public String getWarna() {
        return this.warna;
    }
    
    public void setWarna(String warna) {
        this.warna = warna;
    }
    public int getBiaya() {
        return this.biaya;
    }
    
    public void setBiaya(int biaya) {
        this.biaya = biaya;
    }

    public Boolean getGagalError() {
        return gagalError;
    }

    public void setGagalError(Boolean gagalError) {
        this.gagalError = gagalError;
    }

    public Boolean getGagalMsg() {
        return gagalMsg;
    }

    public void setGagalMsg(Boolean gagalMsg) {
        this.gagalMsg = gagalMsg;
    }

    public String getMsgError() {
        return msgError;
    }

    public void setMsgError(String msgError) {
        this.msgError = msgError;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
    
    
public void save() {
    DAOMobil dmbl = new DAOMobil();
    List<TblMobil> lmbl = dmbl.getbyID(idMobil);
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    if(lmbl.size() > 0) {
        gagalError = true;
        msgError = "ID Sudah Digunakan";
        
    } else {
        DAOMobil mbl = new DAOMobil();
    mbl.addMobil(this);
     gagalMsg = true;
     message = "Data Berhasil Ditambahkan!";
     merek = "";
     tipe = "";
     warna = "";
     biaya = 0;
     idMobil = "";
     gambar = "";
    }
}

public void delete() {
    DAOMobil mbl = new DAOMobil();
    mbl.deleteMobil(idMobil);
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    merek = "";
    tipe = "";
    warna = "";
    biaya = 0;
    idMobil = "";
    gambar = "";
    
    gagalMsg = true;
    message = "Data Berhasil Dihapus";
}

public String getbyid() {
    DAOMobil mbl = new DAOMobil();
    List<TblMobil> lmbl = mbl.getbyID(idMobil);
    merek = "";
    tipe = "";
    warna = "";
    biaya = 0;
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    if(lmbl.size() > 0) {
        TblMobil tp = lmbl.get(0);
        merek = tp.getMerek();
        tipe = tp.getTipe();
        warna = tp.getWarna();
        biaya = tp.getBiaya();
        idMobil = tp.getIdMobil();
        gambar = tp.getGambar();
    } else {
        gagalError = true;
        msgError = "Data Tidak Ditemukan!";
    }
    return "view_mobil";
}

public List<TblMobil> getallrecords() {
    DAOMobil mbl = new DAOMobil();
    List<TblMobil> lmbl = mbl.retrieveTblMobil();
    return lmbl;
}

public void update() {
    DAOMobil mbl = new DAOMobil();
    mbl.updateMobil(this);
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    merek = "";
    tipe = "";
    warna = "";
    biaya = 0;
    idMobil = "";
    gambar = "";
    
    gagalMsg = true;
    message = "Data Berhasil Diubah";
}

public void reset() {
    merek = "";
    tipe = "";
    warna = "";
    biaya = 0;
    idMobil = "";
    gambar = "";
}


}


