package pojo;
// Generated 29/09/2021 4:04:37 PM by Hibernate Tools 4.3.1

import DAO.DAOPelanggan;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblPelanggan generated by hbm2java
 */
@ManagedBean
public class TblPelanggan  implements java.io.Serializable {


     private String idPelanggan;
     private String noKtp;
     private String nama;
     private String alamat;
     private String noTelp;
     private String email;
     private Boolean gagalError;
     private Boolean gagalMsg;
     private String msgError;
     private String message;

    public TblPelanggan() {
    }

    public TblPelanggan(String idPelanggan, String noKtp, String nama, String alamat, String noTelp, String email) {
       this.idPelanggan = idPelanggan;
       this.noKtp = noKtp;
       this.nama = nama;
       this.alamat = alamat;
       this.noTelp = noTelp;
       this.email = email;
    }
   
    public String getIdPelanggan() {
        return this.idPelanggan;
    }
    
    public void setIdPelanggan(String idPelanggan) {
        this.idPelanggan = idPelanggan;
    }
    public String getNoKtp() {
        return this.noKtp;
    }
    
    public void setNoKtp(String noKtp) {
        this.noKtp = noKtp;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getGagalError() {
        return gagalError;
    }

    public void setGagalError(Boolean gagalError) {
        this.gagalError = gagalError;
    }

    public Boolean getGagalMsg() {
        return gagalMsg;
    }

    public void setGagalMsg(Boolean gagalMsg) {
        this.gagalMsg = gagalMsg;
    }

    public String getMsgError() {
        return msgError;
    }

    public void setMsgError(String msgError) {
        this.msgError = msgError;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
    
public void save() {
    DAOPelanggan dplg = new DAOPelanggan();
    List<TblPelanggan> lPlg = dplg.getbyID(idPelanggan);
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    if(lPlg.size() > 0) {
        gagalError = true;
        msgError = "ID Sudah Digunakan";
        
    } else {
        DAOPelanggan plg = new DAOPelanggan();
    plg.addPelanggan(this);
     gagalMsg = true;
     message = "Data Berhasil Ditambahkan!";
     noKtp = "";
     nama = "";
     alamat = "";
     noTelp = "";
     email = "";
     idPelanggan = "";
    }
}

public void delete() {
    DAOPelanggan plg = new DAOPelanggan();
    plg.deletePelanggan(idPelanggan);
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    noKtp = "";
    nama = "";
    alamat = "";
    noTelp = "";
    email = "";
    idPelanggan = "";
    
    gagalMsg = true;
    message = "Data Berhasil Dihapus";
}

public String getbyid() {
    DAOPelanggan plg = new DAOPelanggan();
    List<TblPelanggan> lPlg = plg.getbyID(idPelanggan);
    noKtp = "";
    nama = "";
    alamat = "";
    noTelp = "";
    email = "";;
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    if(lPlg.size() > 0) {
        TblPelanggan tp = lPlg.get(0);
        noKtp = tp.getNoKtp();
        nama = tp.getNama();
        alamat = tp.getAlamat();
        noTelp = tp.getNoTelp();
        email = tp.getEmail();
        idPelanggan = tp.getIdPelanggan();
    } else {
        gagalError = true;
        msgError = "Data Tidak Ditemukan!";
        idPelanggan = "";
    }
    return "view_pelanggan";
}

public List<TblPelanggan> getallrecords() {
    DAOPelanggan plg = new DAOPelanggan();
    List<TblPelanggan> lPlg = plg.retrieveTblPelanggan();
    return lPlg;
}

public void update() {
    DAOPelanggan plg = new DAOPelanggan();
    plg.updatePelanggan(this);
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    noKtp = "";
    nama = "";
    alamat = "";
    noTelp = "";
    email = "";
    idPelanggan = "";
    
    gagalMsg = true;
    message = "Data Berhasil Diubah";
}

public void reset() {
    noKtp = "";
    nama = "";
    alamat = "";
    noTelp = "";
    email = "";
    idPelanggan = "";
}



}


