package pojo;
// Generated 29/09/2021 4:04:37 PM by Hibernate Tools 4.3.1



import DAO.DAOTransaksi;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * TblTrx generated by hbm2java
 */
@ManagedBean
public class TblTrx  implements java.io.Serializable {


     private String idTrx;
     private String pelangganId;
     private Date tanggalSewa;
     private Date tanggalSelesai;
     private String mobilId;
     private int biaya;
     
     private Boolean gagalError;
     private Boolean gagalMsg;
     private String msgError;
     private String message;

    public TblTrx() {
    }

    public TblTrx(String idTrx,  String pelangganId, Date tanggalSewa, Date tanggalSelesai, String mobilId, int biaya) {
       this.idTrx = idTrx;
       this.pelangganId = pelangganId;
       this.tanggalSewa = tanggalSewa;
       this.tanggalSelesai = tanggalSelesai;
       this.mobilId = mobilId;
       this.biaya = biaya;
    }
   
    public String getIdTrx() {
        return this.idTrx;
    }
    
    public void setIdTrx(String idTrx) {
        this.idTrx = idTrx;
    }

    public Date getTanggalSewa() {
        return tanggalSewa;
    }

    public void setTanggalSewa(Date tanggalSewa) {
        this.tanggalSewa = tanggalSewa;
    }

    public Date getTanggalSelesai() {
        return tanggalSelesai;
    }

    public void setTanggalSelesai(Date tanggalSelesai) {
        this.tanggalSelesai = tanggalSelesai;
    }
    
    
    
    public String getPelangganId() {
        return this.pelangganId;
    }
    
    public void setPelangganId(String pelangganId) {
        this.pelangganId = pelangganId;
    }

    public String getMobilId() {
        return mobilId;
    }

    public void setMobilId(String mobilId) {
        this.mobilId = mobilId;
    }

    public int getBiaya() {
        return biaya;
    }

    public void setBiaya(int biaya) {
        this.biaya = biaya;
    }

    public Boolean getGagalError() {
        return gagalError;
    }

    public void setGagalError(Boolean gagalError) {
        this.gagalError = gagalError;
    }

    public Boolean getGagalMsg() {
        return gagalMsg;
    }

    public void setGagalMsg(Boolean gagalMsg) {
        this.gagalMsg = gagalMsg;
    }

    public String getMsgError() {
        return msgError;
    }

    public void setMsgError(String msgError) {
        this.msgError = msgError;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    
public void save() {
    DAOTransaksi dtrx = new DAOTransaksi();
    List<TblTrx> ltrx = dtrx.getbyID(idTrx);
    
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    if(ltrx.size() > 0) {
        gagalError = true;
        msgError = "ID Sudah Digunakan";
        
    } else {
        DAOTransaksi trx = new DAOTransaksi();
    trx.addTrx(this);
    
     gagalMsg = true;
     message = "Data Berhasil Ditambahkan!";
     mobilId = "";
     biaya = 0;
     tanggalSewa = new Date();
     tanggalSelesai = new Date();
     pelangganId = "";
     idTrx = "";
    }
    
}

public void delete() {
    DAOTransaksi trx = new DAOTransaksi();
    trx.deleteTransaksi(idTrx);
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    tanggalSewa = new Date();
    tanggalSelesai = new Date();
    pelangganId = "";
    mobilId = "";
    biaya = 0;
    idTrx = "";
    
    gagalMsg = true;
    message = "Data Berhasil Dihapus";
}

public String getbyid() {
    DAOTransaksi trx = new DAOTransaksi();
    List<TblTrx> ltrx = trx.getbyID(idTrx);
    tanggalSewa = new Date();
    tanggalSelesai = new Date();
    pelangganId = "";
    mobilId = "";
    biaya = 0;
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    if(ltrx.size() > 0) {
        
        TblTrx tp = ltrx.get(0);
        
        mobilId = tp.getMobilId();
        biaya = tp.getBiaya();
        tanggalSewa = tp.getTanggalSewa();
        tanggalSelesai = tp.getTanggalSelesai();
        pelangganId = tp.getPelangganId();
        idTrx = tp.getIdTrx();
    } else {
        gagalError = true;
        msgError = "Data Tidak Ditemukan!";
    }
    return "view_transaksi";
}



public List<TblTrx> getallrecords() {
    DAOTransaksi trx = new DAOTransaksi();
    List<TblTrx> ltrx = trx.retrieveTblTrx();
    return ltrx;
}


public void update() {
    DAOTransaksi trx = new DAOTransaksi();
    trx.updateTrx(this);
    
    gagalError = false;
    msgError = "";
    message = "";
    gagalMsg = false;
    
    mobilId = "";
    biaya = 0;
    tanggalSewa = new Date();
    tanggalSelesai = new Date();
    pelangganId = "";
    idTrx = "";
    
    gagalMsg = true;
    message = "Data Berhasil Diubah";
}

public void reset() {
    mobilId = "";
    biaya = 0;
    tanggalSewa = new Date();
    tanggalSelesai = new Date();
    pelangganId = "";
    idTrx = "";
}



}


